### ISSUE TITLE
Fix PresenterUtils declaration for Nette 3.0a

### ISSUE THREAD

**Issue by Lumeriol** [nittro/nette-bridges#2]
Declaration of Nittro\Bridges\NittroUI\PresenterUtils::getPresenter(bool $throw = true): ?Nette\Application\UI\Presenter must be compatible with Nette\Application\UI\Presenter::getPresenter(bool $throw = true): Nette\Application\UI\Presenter

- and maybe you should use lowercase constants FALSE, TRUE, NULL, etc. as Nette use them?

**Comment by jahudka** [comment]
Okay... well, this is actually Nette's fault, because the `getPresenter()` method is first declared in `Nette\Application\UI\Component` and the return type is nullable there, and then in the overridden `getPresenter()` method declared in `Nette\Application\UI\Presenter` the return type is *not* nullable, which imo breaks contract sort of.. anyway, it can be fixed within `PresenterUtils` by overriding the abstract declaration from `ComponentUtils` to be compatible with `Nette\Application\UI\Presenter`, even though it makes no sense to have that declaration there as the `PresenterUtils` trait doesn't need the method itself.. anyway.. fixed in v2.1.0-alpha2.

**Nb.** Nette actually isn't all that consistent in its code style - both the declaration in `Nette\Application\UI\Component` and the declaration in `Nette\Application\UI\Presenter` use uppercase `TRUE`. Which is funny, because the last time I tried to contribute to a Nette-related project, my *single line* bugfix PR was rejected because I used double quotes instead of single quotes (at a place that used double quotes even *before* my fix). So PLEASE don't EVER talk to me about code style in relation to Nette &co. because I might murder someone 😇

**Comment by Lumeriol** [comment]
For code style, they slowly transforming code to lowercase and single quotes by some recommendations and PSR, but there are many code that is not "fixed" by this styles. So maybe in future.

Thanks for fix of declaration, I know that Nette 3 is still in alpha, so they could change it every day, but today I try Nittro again after a few month and this was first error that I saw :) So maybe I will write to you again, if there will be any more problematic changes.

**Comment by jahudka** [comment]
Anytime :-) I'm not yet using the alpha releases of Nette in any of my projects, so I'm glad when people who *are* take the time to report bugs they run into.

**Comment by klofac** [comment]
I updated Nette and Nittro-Bridges but I got error : 
Declaration of Nette\Application\UI\Component::redirect($destination, $args = Array): void must be compatible with Nittro\Bridges\NittroUI\PresenterUtils::redirect($destination = NULL, $args = Array): void

I have : 
- Nette application v3.0.1
- Nittro nette-bridges v2.1.2

Combination Nette v3.0.0 + Nittro v2.1.1 is ok 

Changelog Nette application v3.0.1 : 
- Component::redirect() removed $code from signature #220 #221

Changelog Nittro nette-bridges v 2.1.2 : 
- Component::redirect() removed $code from signature

But it doesn't work together. What can I do to solve this problem, please ?
